name: Android Publish

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      dotnet-version-target:
        required: true
        type: string
      #xcode-version:
      #  required: true
      #  type: string
      project-file:
        required: true
        type: string
      project-folder:
        required: true
        type: string
      build-config:
        required: true
        type: string
      build-version:
        required: true
        type: string
    secrets:      
      keystore-password:
        required: true
      keystore-alias:
        required: true
      keystore:
        required: true
      #playstore-service-account:
      #  required: true

jobs:
  publish-android:
    runs-on: windows-latest
    name: Android Publish

    env:
      ARTIFACT_DIR: ${{ github.workspace }}\artifacts\android

    steps:
        - name: Setup .NET ${{ inputs.dotnet-version }}
          uses: actions/setup-dotnet@v2
          with:
            dotnet-version: ${{ inputs.dotnet-version }}
      
        - uses: actions/checkout@v3
          name: Checkout the code
      
        # This step might be obsolete at some point as .NET MAUI workloads 
        # are starting to come pre-installed on the GH Actions build agents.
        - name: Install MAUI Workload
          run: dotnet workload install maui --ignore-failed-sources
      
        - name: Restore Dependencies
          run: dotnet restore ${{ inputs.project-file }}

        # ---------------- Version the app ----------------
        # Strategy:
        #   - If triggered by a tag vX.Y.Z -> displayVersion = X.Y.Z
        #   - Else read major.minor from csproj (<ApplicationDisplayVersion> or <Version> or <VersionPrefix>)
        #   - Else fallback "1.0"
        #   - Set patch = github.run_number (auto-increment each run)
        - name: Version the app
          id: version
          shell: pwsh
          run: |
            $ErrorActionPreference = 'Stop'
            $csproj = Join-Path "${{ github.workspace }}" "${{ inputs.project-file }}"
            $content = Get-Content $csproj -Raw
  
            $tag = "${{ github.ref_name }}"
            if ($tag -match '^v\d+\.\d+(\.\d+)?$') {
              $display = $tag.TrimStart('v')
            } else {
              $majorMinor = $null
  
              # Prefer ApplicationDisplayVersion, else Version, else VersionPrefix
              if ($content -match '<ApplicationDisplayVersion>\s*([^<]+)\s*</ApplicationDisplayVersion>') {
                $v = $Matches[1].Trim()
              } elseif ($content -match '<Version>\s*([^<]+)\s*</Version>') {
                $v = $Matches[1].Trim()
              } elseif ($content -match '<VersionPrefix>\s*([^<]+)\s*</VersionPrefix>') {
                $v = $Matches[1].Trim()
              } else {
                $v = '1.0.0'
              }
  
              # Keep only major.minor
              $parts = ($v -split '\.')
              if ($parts.Count -ge 2) {
                $majorMinor = "$($parts[0]).$($parts[1])"
              } else {
                $majorMinor = '1.0'
              }
  
              $patch = $env:GITHUB_RUN_NUMBER
              $display = "$majorMinor.$patch"
            }
  
            # Compute monotonically increasing ApplicationVersion (int)
            $p = ($display -split '\.')
            while ($p.Count -lt 3) { $p += '0' }
            $major = [int]$p[0]; $minor = [int]$p[1]; $patch = [int]$p[2]
            $buildVersion = ($major * 1000000) + ($minor * 1000) + $patch
  
            "displayVersion=$display"    | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            "buildVersion=$buildVersion" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
  
            Write-Host "Resolved displayVersion=$display"
            Write-Host "Resolved buildVersion=$buildVersion"

        # write keystore from secret (base64)
        - name: Write Android keystore from secret
          id: write_keystore
          uses: timheuer/base64-to-file@v1
          with:
            fileDir: '${{ github.workspace }}\${{ inputs.project-folder }}'
            fileName: 'ourkeystore.jks'
            encodedString: ${{ secrets.keystore }}
  
        - name: Publish MAUI Android APK
          run: >
            dotnet publish "${{ inputs.project-file }}"
            -c "${{ inputs.build-config }}"
            -f net9.0-android
            -o "${{ env.ARTIFACT_DIR }}"
            /p:AndroidKeyStore=true
            /p:AndroidSigningKeyStore="${{ steps.write_keystore.outputs.filePath }}"
            /p:AndroidSigningKeyAlias="${{ secrets.keystore-alias }}"
            /p:AndroidSigningKeyPass="${{ secrets.keystore-password }}"
            /p:AndroidSigningStorePass="${{ secrets.keystore-password }}"
            /p:AndroidPackageFormat=apk
            /p:ApplicationDisplayVersion="${{ steps.version.outputs.displayVersion }}"
            /p:ApplicationVersion=${{ steps.version.outputs.buildVersion }}
            --no-restore
  
        - name: List publish output
          shell: pwsh
          run: |
            Write-Host "== Contents of $env:ARTIFACT_DIR =="
            Get-ChildItem -Recurse $env:ARTIFACT_DIR | ForEach-Object { $_.FullName }
  
        - name: Upload Android artifact
          uses: actions/upload-artifact@v4
          with:
            name: android-${{ steps.version.outputs.displayVersion }}
            path: |
              ${{ env.ARTIFACT_DIR }}\*.apk
            if-no-files-found: warn
            retention-days: 14
  
        - name: Create GitHub Release (v${{ steps.version.outputs.displayVersion }})
          uses: softprops/action-gh-release@v2
          with:
            tag_name: v${{ steps.version.outputs.displayVersion }}
            name: Release v${{ steps.version.outputs.displayVersion }}
            generate_release_notes: true
            draft: false
            prerelease: false
            # Use forward slashes for reliability with globs
            files: |
              ${{ github.workspace }}/artifacts/android/*.apk
