name: CD Build

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "**.md"
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - '**/*.yml'
  pull_request:
    branches: [ "master" ]
    
env:
  BUILD_VERSION: '1.0'
  DOTNET_VERSION: 9.0.x
  #XCODE_VERSION: 14.3
  DOTNET_VERSION_TARGETS: net9.0
  CSPROJ_TO_BUILD: FestivalMapper.App/FestivalMapper.App.csproj
  PROJECT_FOLDER: FestivalMapper

jobs:
  vars:
    runs-on: ubuntu-22.04
    outputs:      
      buildVersion: ${{ env.BUILD_VERSION }}
      dotnetVersion: ${{ env.DOTNET_VERSION }}
      #xcodeVersion: ${{ env.XCODE_VERSION }}
      dotnetVersionTargets: ${{ env.DOTNET_VERSION_TARGETS }}
      csprojToBuild: ${{ env.CSPROJ_TO_BUILD }}
      projectFolder: ${{ env.PROJECT_FOLDER }}
    steps:
      - run: echo "Exposing env vars, because they can't be passed to nested workflows."

  build-android:
    needs: vars
    uses: ./.github/workflows/cd-android.yml
    with:
      dotnet-version: ${{ needs.vars.outputs.dotnetVersion }}
      dotnet-version-target: ${{ needs.vars.outputs.dotnetVersionTargets }}
      project-file: ${{ needs.vars.outputs.csprojToBuild }}
      project-folder: ${{ needs.vars.outputs.projectFolder }}
      build-config: 'Release'
      build-version: ${{ needs.vars.outputs.buildVersion }}
    secrets:
      keystore: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      keystore-alias: ${{ secrets.ANDROID_KEY_ALIAS }}
      keystore-password: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      #playstore-service-account: ${{ secrets.PLAYSTORE_SERVICE_ACC }}
